services:
  - type: web
    name: kau-major-credit-api
    env: docker
    plan: free
    region: singapore
    autoDeploy: true
    healthCheckPath: /
    envVars:
      - key: PORT
        value: 8000
